import { JetBrains_Mono } from "next/font/google";
import "./globals.css";


const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Hi, I'm Matthew",
  description: "Generated by create next app",
  themeColor: "#000000", // questo viene usato anche da <meta name="theme-color">
  icons: {
    icon: "/favicon.ico",
    apple: "/icon-192x192.png",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jetBrainsMono.variable}`}>
      <head>
        {/* fallback in caso metadata non basti */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className="antialiased text-[var(--text)] bg-[var(--bg)] min-h-screen">
        {children}
      </body>
    </html>
  );
}
